USE MASTER
GO

IF EXISTS (SELECT * FROM  SYSDATABASES WHERE NAME = 'NONAME')
DROP DATABASE NONAME

CREATE DATABASE NONAME

-- CAU 1.A
CREATE TABLE LOP (
  MALOP VARCHAR(10) PRIMARY KEY,
  TENLOP VARCHAR(50) UNIQUE,
  MAGV VARCHAR(10),
  NGAYBD DATE,
  NGAYKT DATE,
  HOCPHI DECIMAL(10, 2),
  NAMHOC INTEGER,
  CONSTRAINT FK_LOP_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV),
  CONSTRAINT CK_LOP_HOCPHI CHECK (HOCPHI > 0)
);

-- CAU 1.B
CREATE TABLE DANGKY (
  MAHV VARCHAR(10),
  MALOP VARCHAR(10),
  NGAYDK DATE DEFAULT GETDATE(),
  CONSTRAINT PK_DANGKY PRIMARY KEY (MAHV, MALOP),
  CONSTRAINT FK_DANGKY_HOCVIEN FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
  CONSTRAINT FK_DANGKY_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
);

-- CAU 1.C
ALTER TABLE DANGKY
DROP CONSTRAINT FK_DANGKY_LOP;

-- CAU 1.D
ALTER TABLE LOP
ADD CONSTRAINT CK_LOP_NGAYBD_NGAYKT
CHECK (NGAYBD < NGAYKT);

-- CAU 2.A
INSERT INTO LOP (MALOP, TENLOP, MAGV, NGAYBD, NGAYKT, HOCPHI, NAMHOC)
VALUES ('JavaAdv', 'Lập trình Java nâng cao', 'GV001', '2022-01-01', '2022-06-30', 15000000, 2022);

-- CAU 2.B
UPDATE LOP
SET HOCPHI = CASE
  WHEN HOCPHI + 5000000 > 20000000 THEN 20000000
  ELSE HOCPHI + 5000000
END
WHERE MALOP = 'JavaAdv';

-- CAU 2.C
DELETE FROM LOP
WHERE YEAR(NGAYKT) <= 2000;